package ca.qc.bdeb.baldr.ihm;

import ca.qc.bdeb.baldr.noyau.GestionnaireFiltres;
import ca.qc.bdeb.baldr.utils.ArrayUtil;
import ca.qc.bdeb.baldr.utils.Correspondance;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.util.Arrays;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Maxim Bernard
 */
public class FenetreFiltreFichiers extends javax.swing.JDialog {

    private GestionnaireFiltres gestionAjoutFiltre;
    private GestionnaireFiltres gestionExcluFiltre;
    ResourceBundle messages;

    public FenetreFiltreFichiers(
            WindowBaldr parent, GestionnaireFiltres gestionFiltres) {

        super(parent, parent.getMessages().getString("Filter_files"), true);
        messages = ResourceBundle.getBundle("i18n/Baldr");
        initComponents();
        
        // tester taille des composants et arranger...

        setIconImage(parent.iconBaldr);
        setResizable(false);
        pack();
        setLocationRelativeTo(null);

        this.gestionAjoutFiltre = gestionFiltres;
        this.gestionExcluFiltre = new GestionnaireFiltres();//sert a rien mais j'ai peur de l'enlever #NO YOLO
        reinitialiserFiltresAjout();
        reinitialiserFiltresExclu();
        listeAjoutFiltre.setSelectedIndex(0);
        listeExcluFiltre.setSelectedIndex(0);
        btnSupprimerAjoutFiltre.setEnabled(false);
        btnSupprimerExcluFiltre.setEnabled(false);
        listeAjoutFiltre.getSelectionModel().addListSelectionListener(
                new FenetreFiltreFichiersListSelectionListener(listeAjoutFiltre,
                        btnSupprimerAjoutFiltre));
        listeExcluFiltre.getSelectionModel().addListSelectionListener(
                new FenetreFiltreFichiersListSelectionListener(listeExcluFiltre,
                        btnSupprimerExcluFiltre));

        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                listeAjoutFiltre = null;
                listeExcluFiltre = null;
            }
        });

    }

    /**
     * @return Tableau de String dont le format est défini par la classe
     * {@link Correspondance Correspondance} servant à choisir les fichiers à
     * sélectionner.
     */
    public String[] getFiltresAjoutSelectionnes() {
        if (listeAjoutFiltre != null) {
            if (listeAjoutFiltre.getSelectedIndex() == 0) {
                return new String[]{"*"};
            } else {
                List elmsSelectionnes = listeAjoutFiltre.getSelectedValuesList();
                String[] tab = new String[elmsSelectionnes.size()];

                for (int i = 0; i < elmsSelectionnes.size(); i++) {
                    tab[i] = (String) elmsSelectionnes.get(i);
                }

                return tab;
            }
        }
        return null;
    }

    public String[] getFiltresExcluSelectionnes() {
        if (listeExcluFiltre != null) {
            if (listeExcluFiltre.getSelectedIndex() == 0) {
                return new String[]{""};
            } else {
                List elmsSelectionnes = listeExcluFiltre.getSelectedValuesList();
                String[] tab = new String[elmsSelectionnes.size()];

                for (int i = 0; i < elmsSelectionnes.size(); i++) {
                    tab[i] = (String) elmsSelectionnes.get(i);
                }

                return tab;
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeAjoutFiltre = new javax.swing.JList();
        txtAjoutFiltre = new javax.swing.JTextField();
        btnAjoutFiltre = new javax.swing.JButton();
        btnSupprimerAjoutFiltre = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnExcluFiltre = new javax.swing.JButton();
        lblAjoutFiltre = new java.awt.Label();
        txtExcluFiltre = new javax.swing.JTextField();
        lblExcluFiltre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeExcluFiltre = new javax.swing.JList();
        btnSupprimerExcluFiltre = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setModal(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setViewportView(listeAjoutFiltre);

        btnAjoutFiltre.setText(messages.getString("Add_filter"));
        btnAjoutFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutFiltreActionPerformed(evt);
            }
        });

        btnSupprimerAjoutFiltre.setText(messages.getString("Delete_filter"));
        btnSupprimerAjoutFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerAjoutFiltreActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnExcluFiltre.setText(messages.getString("Exclude_filter"));
        btnExcluFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluFiltreActionPerformed(evt);
            }
        });

        lblAjoutFiltre.setText(messages.getString("Insert_filter"));

        lblExcluFiltre.setText(messages.getString("Insert_exclusion_filter"));

        jScrollPane2.setViewportView(listeExcluFiltre);

        btnSupprimerExcluFiltre.setText(messages.getString("Remove_excluded_filter"));
        btnSupprimerExcluFiltre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerExcluFiltreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAjoutFiltre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAjoutFiltre)
                            .addComponent(btnSupprimerAjoutFiltre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(btnAjoutFiltre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExcluFiltre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExcluFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSupprimerExcluFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAjoutFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExcluFiltre))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAjoutFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExcluFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjoutFiltre)
                    .addComponent(btnExcluFiltre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSupprimerAjoutFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSupprimerExcluFiltre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAjoutFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutFiltreActionPerformed
        if (!txtAjoutFiltre.getText().equals("")) {
            gestionAjoutFiltre.ajouterFiltre(txtAjoutFiltre.getText());
            gestionAjoutFiltre.enregistrerFiltresAjout();
            reinitialiserFiltresAjout();
            txtAjoutFiltre.setText("");
        }
    }//GEN-LAST:event_btnAjoutFiltreActionPerformed

    private void btnSupprimerAjoutFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerAjoutFiltreActionPerformed
        Object[] selectionnes = listeAjoutFiltre.getSelectedValuesList().toArray();

        // Si "Tous les fichiers" est sélectionné, on l'enlève
        if (listeAjoutFiltre.getSelectedIndex() == 0) {
            selectionnes = Arrays.copyOfRange(
                    selectionnes, 1, selectionnes.length);
        }

        for (Object item : selectionnes) {
            gestionAjoutFiltre.suprimerFiltreAjout((String) item);
        }

        gestionAjoutFiltre.enregistrerFiltresAjout();

        reinitialiserFiltresAjout();
    }//GEN-LAST:event_btnSupprimerAjoutFiltreActionPerformed

    private void btnExcluFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluFiltreActionPerformed
        if (!txtExcluFiltre.getText().equals("")) {
            gestionAjoutFiltre.exclureFiltre(txtExcluFiltre.getText());
            gestionAjoutFiltre.enregistrerFiltresExclu();
            reinitialiserFiltresExclu();
            txtExcluFiltre.setText("");
        }
    }//GEN-LAST:event_btnExcluFiltreActionPerformed

    private void btnSupprimerExcluFiltreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerExcluFiltreActionPerformed
        Object[] selectionnes = listeExcluFiltre.getSelectedValuesList().toArray();

        // Si "Tous les fichiers" est sélectionné, on l'enlève
        if (listeExcluFiltre.getSelectedIndex() == 0) {
            selectionnes = Arrays.copyOfRange(
                    selectionnes, 1, selectionnes.length);
        }

        for (Object item : selectionnes) {
            gestionAjoutFiltre.suprimerFiltreExclu((String) item);
        }

        gestionAjoutFiltre.enregistrerFiltresExclu();

        reinitialiserFiltresExclu();
    }//GEN-LAST:event_btnSupprimerExcluFiltreActionPerformed

    private void reinitialiserFiltresAjout() {
        String[] tabFiltres = ArrayUtil.prependString(
                gestionAjoutFiltre.getFiltresAjout(), messages.getString("All_files"));

        listeAjoutFiltre.setListData(tabFiltres);
    }

    private void reinitialiserFiltresExclu() {
        String[] tabFiltres = ArrayUtil.prependString(
                gestionAjoutFiltre.getFiltresExclu(), messages.getString("No_files"));

        listeExcluFiltre.setListData(tabFiltres);
    }

    /**
     * Reçoit les événements de changement de sélection de la liste, et s'assure
     * qu'au moins un élément soit toujours sélectionné. Si l'utilisateur
     * désélectionne tout, le premier doit être automatiquement re-sélectionné.
     */
    private class FenetreFiltreFichiersListSelectionListener
            implements ListSelectionListener {

        private JList liste;
        private JButton btnSupprimer;

        public FenetreFiltreFichiersListSelectionListener(JList liste,
                JButton btnSupprimer) {
            this.liste = liste;
            this.btnSupprimer = btnSupprimer;

        }

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (liste.getSelectedIndex() == -1) {
                liste.setSelectedIndex(0);
            } else {
                int[] selected = liste.getSelectedIndices();

                if (selected.length == 1 && selected[0] == 0) {
                    btnSupprimer.setEnabled(false);
                    btnSupprimer.setText(messages.getString("Delete_filter"));
                } else {
                    btnSupprimer.setEnabled(true);
                    btnSupprimer.setText(selected.length > 1
                            ? messages.getString("Remove_filters")
                            : messages.getString("Delete_filter"));
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjoutFiltre;
    private javax.swing.JButton btnExcluFiltre;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSupprimerAjoutFiltre;
    private javax.swing.JButton btnSupprimerExcluFiltre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label lblAjoutFiltre;
    private javax.swing.JLabel lblExcluFiltre;
    private javax.swing.JList listeAjoutFiltre;
    private javax.swing.JList listeExcluFiltre;
    private javax.swing.JTextField txtAjoutFiltre;
    private javax.swing.JTextField txtExcluFiltre;
    // End of variables declaration//GEN-END:variables
}
