/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.qc.bdeb.baldr.ihm;

/**
 *
 * @author Clément
 */
public class PanelContentFile extends javax.swing.JPanel {

    /**
     * Creates new form PanelContentFile
     */
    public PanelContentFile() {
        initComponents();
        labelGauche.setText("");

        labelDroite.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        zoneDroite = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        zoneGauche = new javax.swing.JTextArea();
        labelGauche = new javax.swing.JLabel();
        labelDroite = new javax.swing.JLabel();

        zoneDroite.setColumns(20);
        zoneDroite.setRows(5);
        jScrollPane1.setViewportView(zoneDroite);

        zoneGauche.setColumns(20);
        zoneGauche.setRows(5);
        zoneGauche.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(zoneGauche);

        labelGauche.setText("labelGauche");

        labelDroite.setText("labelDroite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDroite)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGauche)
                    .addComponent(labelDroite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDroite;
    private javax.swing.JLabel labelGauche;
    private javax.swing.JTextArea zoneDroite;
    private javax.swing.JTextArea zoneGauche;
    // End of variables declaration//GEN-END:variables

    public void setDroite(String nomFichier, String texteFichier){
        labelDroite.setText(nomFichier);
        zoneDroite.setText(texteFichier);
        zoneDroite.setCaretPosition(0);
    }
    
    public void setGauche(String nomFichier, String texteFichier){
        labelGauche.setText(nomFichier);
        zoneGauche.setText(texteFichier);
        zoneGauche.setCaretPosition(0);
    }

}
